### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by Mazaalto** [joonaspartanen/tsoha-forum#4]
Latasin projektin 2.6. klo 15.13. 
Projektisi näyttää erittäin hyvältä ja näytät edistyneen todella hyvin.

Muutamia huomioita:

Aiheiden postaus onnistui mainiosti, mietin voisiko aihetägit olla pidempiä? Nyt nykyinen 10-kirjaimen yläraja rajoitti perhokalastus kommenttini tagia. Voisiko se olla 20 kirjainta? Vaikuttaako se sommitteluusi sivulla? Tämä siis https://tsoha-forum-app.herokuapp.com/topics/new herokussa tai sovelluksessa uuden tietueen luonnissa.

Luokat oli fiksusti nimetty ja koodi oli siistiä ja selkeätä.  

Tietokantakaavio oli informatiivinen ja selkeä. Lisäksi siitä jo pystyi hahmottamaan sovelluksen toimintaa. 

Uuden käyttäjän luominen ja kirjautuminen onnistui hyvin.

Koodista on vaikea keksiä korjauksia, varsinkaan kun koodi on vielä kesken. Mielestäni olet hienosti impelentoinut kurssimateriaalia ja lisännyt omana twistinä ulkoasua ja kuvien integroiminen postauksiin oli hieno lisä.

MyProfile sivusta tuli https://tsoha-forum-app.herokuapp.com/auth/users/ tuli notfoundia. Varmaan siis se vielä kesken? Voisiko ohjata myös kirjautumissivulle?

Menestystä loppu kurssille!

**Comment by joonaspartanen** [comment]
Kiitos hyvästä palautteesta!

Tageja täytyy tosiaan pidentää.

Täytyypä myös tutkailla, mikä profiilisivussa on vikana. Polussa pitäisi olla mukana käyttäjän id eli esim. https://tsoha-forum-app.herokuapp.com/auth/users/1 mutta ehkä siellä on jossain rikkinäinen linkki.
