### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by MiguelSombrero** [joonaspartanen/tsoha-forum#5]
Projektin zip-paketti ladattu 14.6.2020 kello 6:34.

Testattu seuraavia toiminnallisuuksia:

-	Käyttäjän rekisteröiminen
o	Lomakkeella on validointi, eikä esimerkiksi tyhjän käyttäjätunnuksen tai salasanan syöttäminen onnistu
-	Kirjautuminen
o	Sovellus ilmoittaa väärästä käyttäjätunnuksesta ja salasanasta. Tietoturvaa ajatellen voisi pohtia, onko parempi ettei sovellus ilmoita käyttäjälle onko käyttäjätunnus oikein. Tämä antaa potentiaaliselle hyökkääjälle ”liikaa” informaatiota
-	Uuden viestiketjun luominen
o	Lomakkeen validointi toimii.
o	Tags kentässä voisi olla jokin vinkki siitä, että tagit tulee erottaa toisistaan pilkulla
-	Viestiketjun poisto
-	Viestiketjun haku
o	Viestien haku toimii hyvin. Käyttäjäystävällisyyttä voisi lisätä vielä se, jos hakutulokset sivulla olisi myös hakulomake. Siis siten, että käyttäjä voi tehdä uuden haun suoraan hakutulokset sivulta, siirtymättä yläpalkin kautta ”Search topics” sivulle
-	Postauksen lisääminen viestiketjuun
o	Validointi toimii. Hetken sain miettiä, miten postaus lisätään viestiketjuun. Viestiketjun avaaminen voisi olla intuitiivisempi, esimerkiksi klikkaamalla mitä tahansa kohtaa viestiketjusta tjs.
-	Postauksen päivittäminen ja poistaminen
-	Postauksen tykkääminen
-	Profiilitekstin päivittäminen
-	Uloskirjautuminen

Projektin rakenne on selkeä ja koodia on helppo lukea. Sovellus itsessään on intuitiivinen ja sitä on helppo käyttää. Sovelluksessa on käytetty myös tyylikirjastoa ja ulkoasu on nätti. Validoinnit ja auktorisoinnit toimii. Kaikin puolin mukava kokemus :)

Erittäin hyvä!

**Comment by joonaspartanen** [comment]
Kiitoksia arviosta! En ollut tullut montaa näistä asioista ajatelleeksi ollenkaan, eli oikein hyödyllisiä kommentteja.
