### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Nurou** [joonaspartanen/tsoha-forum#6]
**Time of review:** 21.18.17 Eastern European Summer Time

# **What I did**

- Went through the documentation
- Tested the functionality of the application running on Heroku
- Downloaded the project and attempted to run it according to the installation guide
- Skimmed through the project files and reviewed the code on a higher level
- Ran both performance & accessibility audits

# **General Comments**

- In nutshell: really nice work.
- The application is fully functional - well done!
- Everything seems to be working as intended
- The UI is refreshingly neat - generally pleasant to navigate and use. It's great to see that you've put effort into it. I especially appreciate the attention to detail, e.g the bird favicon :)
- Documentation is 👌🏽

# **Functionality**

Some comments on the application's functionality:

- I could not get the application to run locally since I was unable to install all of the dependencies - the download encountered an error installing 'psycopg2'. This seems to be an issue related to some PSQL configuration. I did not have time to go and work out a solution to it.
- Likes were not showing up on my profile even after I had liked a post - perhaps this hasn't been implemented yet? I might have missed something.
- The database is in most part normalised. A further normalisation suggestion would be to isolate the user.is_admin into its own 'Role' table.
- Linked to the idea above, the application routes could do with role-based protection. This way regular users would only see/be able to access routes that are intended for them, and vice-versa.
- There is functionality for deleting stuff, such as whole topics. This is great, but it would also be useful to warn the user/admin prior to any persistent deletion. This could be achieved, e.g. through a window confirm pop-up. That way, the user would have a chance to reconsider their intended action.

# **Documentation**

- The documentation is comprehensive and clear. Everything required has been included, inc. all the queries. Good use of images as well. Well done!
- It would be a good idea to put the link to the production app somewhere more noticeable, such as the project description. It's currently right at the bottom of the README page, which people can easily miss.
- The only suggestion I would have is to perhaps include user stories. You've described the *what* of the functionality well, but there could be a little more on the *why*.

# **Code Quality**

- Great use of abstraction. Everything is neatly organised for the most part, and navigating the project is straightforward.
- There doesn't appear to be any sensitive data exposed. Good use of environment variables.
- An improvement suggestion would be to use a Base database model class to abstract away fields that are common to different models in your project, such as the id and the date fields.
- Packages have generally been well utilised.
- I like that you wrote some custom JavaScript to handle UI events :D
- Some links could be converted to use 'url_for', e.g. avatar link your topic template

# **Usability & Accessibility**

- 1+ for the tidiness of the HTML
- UI is clean and usable
- The semantics of your HTML could be improved a bit, e.g. div element seems to be overused. There are quite a few instances where it could be swapped with section, article, etc.
- The accessibility audit hinted at some improvements - you can run axe from your dev tools (in Chrome at least) and make improvements based on the suggestions. There seem to be minor issues with missing labels and colour contrast.

**Comment by joonaspartanen** [comment]
Wow, thank you for the very detailed and comprehensive review! :) This is very useful at this point.
